# Site wide configuration

title: Yugen
locale: en_US
description: Rachith's blog
logo: Photograph copy.png
url: https://rachithaiyappa.github.io

# Jekyll configuration


permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false
  
timezone: Europe/Berlin
future: true

disqus:
  shortname: "rachithaiyappa-github-io"

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

comments: true

# Site owner
owner:
  name: Rachith Aiyappa
  avatar: 
  email: rachithaiyappa96@gmail.com
  disqus-shortname: sosimpletheme
  twitter: rachithaiyappa
  facebook: 
  github: rachithaiyappa
  stackexchange:
  linkedin:
  instagram: 
  flickr:
  tumblr: 
  pinterest:
  weibo:
  google:
    plus: 
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
