# Site wide configuration

title: Yugen
locale: en_US
description: Rachith's ordered chaos
logo: Photograph copy.png
url: https://rachithaiyappa.github.io

# Jekyll configuration


permalink:   /:categories/:title/
markdown:    GFM
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
plugins:
  - jekyll-seo-tag

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false
  
timezone: Europe/Berlin
future: true

disqus:
  shortname: "rachithaiyappa-github-io"

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

comments: true

# Site owner
owner:
  name: Rachith Aiyappa
  avatar: 
  disqus-shortname: sosimpletheme
  twitter: rachithaiyappa
  facebook: 
  github: rachithaiyappa
  email: rachithaiyappa96@gmail.com
  stackexchange:
  linkedin: rachith-aiyappa-388140113/
  instagram: 
  flickr:
  tumblr: 
  pinterest:
  weibo:
  google:
    plus: 
    email : rachithaiyappa96@gmail.com
    analytics: UA-170240696-1
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
  google_analytics: UA-146256299-1
  
  footer_links:
  - title: Twitter
    url: https://twitter.com/rachithaiyappa
    icon: fab fa-twitter-square
  - title: Email
    url: mailto:rachithaiyappa96@gmail.com
    icon: fab fa-envelope-square
